version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - Luc41
  assignees:
  - Luc41
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: "@quasar/extras"
    versions:
    - 1.10.0
    - 1.10.1
    - 1.10.2
    - 1.10.3
    - 1.9.14
    - 1.9.15
    - 1.9.16
    - 1.9.17
    - 1.9.18
    - 1.9.19
    - 1.9.20
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: quasar
    versions:
    - 1.15.1
    - 1.15.2
    - 1.15.3
    - 1.15.4
    - 1.15.5
    - 1.15.6
    - 1.15.7
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
    - 1.1.3
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
